
title: My Resume
url: 'http://joycecao.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Joyce Cao  ## put your name
title: 'Electrical and Computer Engineering Student'  ## your title
location: Ithaca, NY </br> Tucson, AZ


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
